<CreatureListWid>:
    ScrollView:
        size: self.size
        GridLayout:
            id: conteiner
            padding:[10,10,10,10]
            spacing: 5
            size_hint_y: None
            cols: 1
            row_default_height: root.height*0.2
            height: self.minimum_height

<NewCreatureButton>:
    font_size: self.height*0.5
    text: '+'
    on_press: root.creature_new()